# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designSlnELa.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 610)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label1 = QLabel(self.centralwidget)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 40, 16, 16))
        self.label1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(10, 80, 16, 16))
        self.label2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label3 = QLabel(self.centralwidget)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(10, 120, 16, 16))
        self.label3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label4 = QLabel(self.centralwidget)
        self.label4.setObjectName(u"label4")
        self.label4.setGeometry(QRect(10, 160, 16, 16))
        self.label4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label5 = QLabel(self.centralwidget)
        self.label5.setObjectName(u"label5")
        self.label5.setGeometry(QRect(10, 200, 16, 16))
        self.label5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label6 = QLabel(self.centralwidget)
        self.label6.setObjectName(u"label6")
        self.label6.setGeometry(QRect(10, 240, 16, 16))
        self.label6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label7 = QLabel(self.centralwidget)
        self.label7.setObjectName(u"label7")
        self.label7.setGeometry(QRect(10, 280, 16, 16))
        self.label7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label8 = QLabel(self.centralwidget)
        self.label8.setObjectName(u"label8")
        self.label8.setGeometry(QRect(10, 320, 16, 16))
        self.label8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label9 = QLabel(self.centralwidget)
        self.label9.setObjectName(u"label9")
        self.label9.setGeometry(QRect(10, 360, 16, 16))
        self.label9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label10 = QLabel(self.centralwidget)
        self.label10.setObjectName(u"label10")
        self.label10.setGeometry(QRect(10, 400, 16, 16))
        self.label10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label11 = QLabel(self.centralwidget)
        self.label11.setObjectName(u"label11")
        self.label11.setGeometry(QRect(10, 440, 16, 16))
        self.label11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label12 = QLabel(self.centralwidget)
        self.label12.setObjectName(u"label12")
        self.label12.setGeometry(QRect(10, 480, 16, 16))
        self.label12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label13 = QLabel(self.centralwidget)
        self.label13.setObjectName(u"label13")
        self.label13.setGeometry(QRect(10, 520, 16, 16))
        self.label13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_1A = QLineEdit(self.centralwidget)
        self.lineEdit_1A.setObjectName(u"lineEdit_1A")
        self.lineEdit_1A.setGeometry(QRect(40, 35, 90, 30))
        self.lineEdit_2A = QLineEdit(self.centralwidget)
        self.lineEdit_2A.setObjectName(u"lineEdit_2A")
        self.lineEdit_2A.setGeometry(QRect(40, 75, 90, 30))
        self.lineEdit_3A = QLineEdit(self.centralwidget)
        self.lineEdit_3A.setObjectName(u"lineEdit_3A")
        self.lineEdit_3A.setGeometry(QRect(40, 115, 90, 30))
        self.lineEdit_4A = QLineEdit(self.centralwidget)
        self.lineEdit_4A.setObjectName(u"lineEdit_4A")
        self.lineEdit_4A.setGeometry(QRect(40, 155, 90, 30))
        self.lineEdit_5A = QLineEdit(self.centralwidget)
        self.lineEdit_5A.setObjectName(u"lineEdit_5A")
        self.lineEdit_5A.setGeometry(QRect(40, 195, 90, 30))
        self.lineEdit_6A = QLineEdit(self.centralwidget)
        self.lineEdit_6A.setObjectName(u"lineEdit_6A")
        self.lineEdit_6A.setGeometry(QRect(40, 235, 90, 30))
        self.lineEdit_7A = QLineEdit(self.centralwidget)
        self.lineEdit_7A.setObjectName(u"lineEdit_7A")
        self.lineEdit_7A.setGeometry(QRect(40, 275, 90, 30))
        self.lineEdit_8A = QLineEdit(self.centralwidget)
        self.lineEdit_8A.setObjectName(u"lineEdit_8A")
        self.lineEdit_8A.setGeometry(QRect(40, 315, 90, 30))
        self.lineEdit_9A = QLineEdit(self.centralwidget)
        self.lineEdit_9A.setObjectName(u"lineEdit_9A")
        self.lineEdit_9A.setGeometry(QRect(40, 355, 90, 30))
        self.lineEdit_10A = QLineEdit(self.centralwidget)
        self.lineEdit_10A.setObjectName(u"lineEdit_10A")
        self.lineEdit_10A.setGeometry(QRect(40, 395, 90, 30))
        self.lineEdit_11A = QLineEdit(self.centralwidget)
        self.lineEdit_11A.setObjectName(u"lineEdit_11A")
        self.lineEdit_11A.setGeometry(QRect(40, 435, 90, 30))
        self.lineEdit_12A = QLineEdit(self.centralwidget)
        self.lineEdit_12A.setObjectName(u"lineEdit_12A")
        self.lineEdit_12A.setGeometry(QRect(40, 475, 90, 30))
        self.lineEdit_13A = QLineEdit(self.centralwidget)
        self.lineEdit_13A.setObjectName(u"lineEdit_13A")
        self.lineEdit_13A.setGeometry(QRect(40, 515, 90, 30))
        self.Column1 = QLabel(self.centralwidget)
        self.Column1.setObjectName(u"Column1")
        self.Column1.setGeometry(QRect(75, 10, 20, 16))
        self.Column1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_5B = QLineEdit(self.centralwidget)
        self.lineEdit_5B.setObjectName(u"lineEdit_5B")
        self.lineEdit_5B.setGeometry(QRect(135, 195, 90, 30))
        self.lineEdit_13B = QLineEdit(self.centralwidget)
        self.lineEdit_13B.setObjectName(u"lineEdit_13B")
        self.lineEdit_13B.setGeometry(QRect(135, 515, 90, 30))
        self.lineEdit_2B = QLineEdit(self.centralwidget)
        self.lineEdit_2B.setObjectName(u"lineEdit_2B")
        self.lineEdit_2B.setGeometry(QRect(135, 75, 90, 30))
        self.lineEdit_12B = QLineEdit(self.centralwidget)
        self.lineEdit_12B.setObjectName(u"lineEdit_12B")
        self.lineEdit_12B.setGeometry(QRect(135, 475, 90, 30))
        self.Column2 = QLabel(self.centralwidget)
        self.Column2.setObjectName(u"Column2")
        self.Column2.setGeometry(QRect(170, 10, 20, 16))
        self.Column2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_6B = QLineEdit(self.centralwidget)
        self.lineEdit_6B.setObjectName(u"lineEdit_6B")
        self.lineEdit_6B.setGeometry(QRect(135, 235, 90, 30))
        self.lineEdit_1B = QLineEdit(self.centralwidget)
        self.lineEdit_1B.setObjectName(u"lineEdit_1B")
        self.lineEdit_1B.setGeometry(QRect(135, 35, 90, 30))
        self.lineEdit_8B = QLineEdit(self.centralwidget)
        self.lineEdit_8B.setObjectName(u"lineEdit_8B")
        self.lineEdit_8B.setGeometry(QRect(135, 315, 90, 30))
        self.lineEdit_10B = QLineEdit(self.centralwidget)
        self.lineEdit_10B.setObjectName(u"lineEdit_10B")
        self.lineEdit_10B.setGeometry(QRect(135, 395, 90, 30))
        self.lineEdit_11B = QLineEdit(self.centralwidget)
        self.lineEdit_11B.setObjectName(u"lineEdit_11B")
        self.lineEdit_11B.setGeometry(QRect(135, 435, 90, 30))
        self.lineEdit_7B = QLineEdit(self.centralwidget)
        self.lineEdit_7B.setObjectName(u"lineEdit_7B")
        self.lineEdit_7B.setGeometry(QRect(135, 275, 90, 30))
        self.lineEdit_9B = QLineEdit(self.centralwidget)
        self.lineEdit_9B.setObjectName(u"lineEdit_9B")
        self.lineEdit_9B.setGeometry(QRect(135, 355, 90, 30))
        self.lineEdit_3B = QLineEdit(self.centralwidget)
        self.lineEdit_3B.setObjectName(u"lineEdit_3B")
        self.lineEdit_3B.setGeometry(QRect(135, 115, 90, 30))
        self.lineEdit_4B = QLineEdit(self.centralwidget)
        self.lineEdit_4B.setObjectName(u"lineEdit_4B")
        self.lineEdit_4B.setGeometry(QRect(135, 155, 90, 30))
        self.lineEdit_3C = QLineEdit(self.centralwidget)
        self.lineEdit_3C.setObjectName(u"lineEdit_3C")
        self.lineEdit_3C.setGeometry(QRect(230, 115, 90, 30))
        self.lineEdit_7C = QLineEdit(self.centralwidget)
        self.lineEdit_7C.setObjectName(u"lineEdit_7C")
        self.lineEdit_7C.setGeometry(QRect(230, 275, 90, 30))
        self.lineEdit_12C = QLineEdit(self.centralwidget)
        self.lineEdit_12C.setObjectName(u"lineEdit_12C")
        self.lineEdit_12C.setGeometry(QRect(230, 475, 90, 30))
        self.lineEdit_11C = QLineEdit(self.centralwidget)
        self.lineEdit_11C.setObjectName(u"lineEdit_11C")
        self.lineEdit_11C.setGeometry(QRect(230, 435, 90, 30))
        self.Column3 = QLabel(self.centralwidget)
        self.Column3.setObjectName(u"Column3")
        self.Column3.setGeometry(QRect(265, 10, 20, 16))
        self.Column3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_1C = QLineEdit(self.centralwidget)
        self.lineEdit_1C.setObjectName(u"lineEdit_1C")
        self.lineEdit_1C.setGeometry(QRect(230, 35, 90, 30))
        self.lineEdit_6C = QLineEdit(self.centralwidget)
        self.lineEdit_6C.setObjectName(u"lineEdit_6C")
        self.lineEdit_6C.setGeometry(QRect(230, 235, 90, 30))
        self.lineEdit_2C = QLineEdit(self.centralwidget)
        self.lineEdit_2C.setObjectName(u"lineEdit_2C")
        self.lineEdit_2C.setGeometry(QRect(230, 75, 90, 30))
        self.lineEdit_13C = QLineEdit(self.centralwidget)
        self.lineEdit_13C.setObjectName(u"lineEdit_13C")
        self.lineEdit_13C.setGeometry(QRect(230, 515, 90, 30))
        self.lineEdit_4C = QLineEdit(self.centralwidget)
        self.lineEdit_4C.setObjectName(u"lineEdit_4C")
        self.lineEdit_4C.setGeometry(QRect(230, 155, 90, 30))
        self.lineEdit_5C = QLineEdit(self.centralwidget)
        self.lineEdit_5C.setObjectName(u"lineEdit_5C")
        self.lineEdit_5C.setGeometry(QRect(230, 195, 90, 30))
        self.lineEdit_9C = QLineEdit(self.centralwidget)
        self.lineEdit_9C.setObjectName(u"lineEdit_9C")
        self.lineEdit_9C.setGeometry(QRect(230, 355, 90, 30))
        self.lineEdit_10C = QLineEdit(self.centralwidget)
        self.lineEdit_10C.setObjectName(u"lineEdit_10C")
        self.lineEdit_10C.setGeometry(QRect(230, 395, 90, 30))
        self.lineEdit_8C = QLineEdit(self.centralwidget)
        self.lineEdit_8C.setObjectName(u"lineEdit_8C")
        self.lineEdit_8C.setGeometry(QRect(230, 315, 90, 30))
        self.lineEdit_7D = QLineEdit(self.centralwidget)
        self.lineEdit_7D.setObjectName(u"lineEdit_7D")
        self.lineEdit_7D.setGeometry(QRect(325, 275, 90, 30))
        self.lineEdit_13D = QLineEdit(self.centralwidget)
        self.lineEdit_13D.setObjectName(u"lineEdit_13D")
        self.lineEdit_13D.setGeometry(QRect(325, 515, 90, 30))
        self.lineEdit_3D = QLineEdit(self.centralwidget)
        self.lineEdit_3D.setObjectName(u"lineEdit_3D")
        self.lineEdit_3D.setGeometry(QRect(325, 115, 90, 30))
        self.lineEdit_5D = QLineEdit(self.centralwidget)
        self.lineEdit_5D.setObjectName(u"lineEdit_5D")
        self.lineEdit_5D.setGeometry(QRect(325, 195, 90, 30))
        self.lineEdit_12D = QLineEdit(self.centralwidget)
        self.lineEdit_12D.setObjectName(u"lineEdit_12D")
        self.lineEdit_12D.setGeometry(QRect(325, 475, 90, 30))
        self.lineEdit_11D = QLineEdit(self.centralwidget)
        self.lineEdit_11D.setObjectName(u"lineEdit_11D")
        self.lineEdit_11D.setGeometry(QRect(325, 435, 90, 30))
        self.lineEdit_4D = QLineEdit(self.centralwidget)
        self.lineEdit_4D.setObjectName(u"lineEdit_4D")
        self.lineEdit_4D.setGeometry(QRect(325, 155, 90, 30))
        self.lineEdit_1D = QLineEdit(self.centralwidget)
        self.lineEdit_1D.setObjectName(u"lineEdit_1D")
        self.lineEdit_1D.setGeometry(QRect(325, 35, 90, 30))
        self.lineEdit_8D = QLineEdit(self.centralwidget)
        self.lineEdit_8D.setObjectName(u"lineEdit_8D")
        self.lineEdit_8D.setGeometry(QRect(325, 315, 90, 30))
        self.lineEdit_6D = QLineEdit(self.centralwidget)
        self.lineEdit_6D.setObjectName(u"lineEdit_6D")
        self.lineEdit_6D.setGeometry(QRect(325, 235, 90, 30))
        self.Column4 = QLabel(self.centralwidget)
        self.Column4.setObjectName(u"Column4")
        self.Column4.setGeometry(QRect(360, 10, 20, 16))
        self.Column4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2D = QLineEdit(self.centralwidget)
        self.lineEdit_2D.setObjectName(u"lineEdit_2D")
        self.lineEdit_2D.setGeometry(QRect(325, 75, 90, 30))
        self.lineEdit_9D = QLineEdit(self.centralwidget)
        self.lineEdit_9D.setObjectName(u"lineEdit_9D")
        self.lineEdit_9D.setGeometry(QRect(325, 355, 90, 30))
        self.lineEdit_10D = QLineEdit(self.centralwidget)
        self.lineEdit_10D.setObjectName(u"lineEdit_10D")
        self.lineEdit_10D.setGeometry(QRect(325, 395, 90, 30))
        self.lineEdit_4E = QLineEdit(self.centralwidget)
        self.lineEdit_4E.setObjectName(u"lineEdit_4E")
        self.lineEdit_4E.setGeometry(QRect(420, 155, 90, 30))
        self.lineEdit_11E = QLineEdit(self.centralwidget)
        self.lineEdit_11E.setObjectName(u"lineEdit_11E")
        self.lineEdit_11E.setGeometry(QRect(420, 435, 90, 30))
        self.lineEdit_1E = QLineEdit(self.centralwidget)
        self.lineEdit_1E.setObjectName(u"lineEdit_1E")
        self.lineEdit_1E.setGeometry(QRect(420, 35, 90, 30))
        self.lineEdit_6E = QLineEdit(self.centralwidget)
        self.lineEdit_6E.setObjectName(u"lineEdit_6E")
        self.lineEdit_6E.setGeometry(QRect(420, 235, 90, 30))
        self.lineEdit_2E = QLineEdit(self.centralwidget)
        self.lineEdit_2E.setObjectName(u"lineEdit_2E")
        self.lineEdit_2E.setGeometry(QRect(420, 75, 90, 30))
        self.Column5 = QLabel(self.centralwidget)
        self.Column5.setObjectName(u"Column5")
        self.Column5.setGeometry(QRect(455, 10, 20, 16))
        self.Column5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_13E = QLineEdit(self.centralwidget)
        self.lineEdit_13E.setObjectName(u"lineEdit_13E")
        self.lineEdit_13E.setGeometry(QRect(420, 515, 90, 30))
        self.lineEdit_3E = QLineEdit(self.centralwidget)
        self.lineEdit_3E.setObjectName(u"lineEdit_3E")
        self.lineEdit_3E.setGeometry(QRect(420, 115, 90, 30))
        self.lineEdit_8E = QLineEdit(self.centralwidget)
        self.lineEdit_8E.setObjectName(u"lineEdit_8E")
        self.lineEdit_8E.setGeometry(QRect(420, 315, 90, 30))
        self.lineEdit_9E = QLineEdit(self.centralwidget)
        self.lineEdit_9E.setObjectName(u"lineEdit_9E")
        self.lineEdit_9E.setGeometry(QRect(420, 355, 90, 30))
        self.lineEdit_5E = QLineEdit(self.centralwidget)
        self.lineEdit_5E.setObjectName(u"lineEdit_5E")
        self.lineEdit_5E.setGeometry(QRect(420, 195, 90, 30))
        self.lineEdit_7E = QLineEdit(self.centralwidget)
        self.lineEdit_7E.setObjectName(u"lineEdit_7E")
        self.lineEdit_7E.setGeometry(QRect(420, 275, 90, 30))
        self.lineEdit_12E = QLineEdit(self.centralwidget)
        self.lineEdit_12E.setObjectName(u"lineEdit_12E")
        self.lineEdit_12E.setGeometry(QRect(420, 475, 90, 30))
        self.lineEdit_10E = QLineEdit(self.centralwidget)
        self.lineEdit_10E.setObjectName(u"lineEdit_10E")
        self.lineEdit_10E.setGeometry(QRect(420, 395, 90, 30))
        self.lineEdit_5F = QLineEdit(self.centralwidget)
        self.lineEdit_5F.setObjectName(u"lineEdit_5F")
        self.lineEdit_5F.setGeometry(QRect(515, 195, 90, 30))
        self.lineEdit_13F = QLineEdit(self.centralwidget)
        self.lineEdit_13F.setObjectName(u"lineEdit_13F")
        self.lineEdit_13F.setGeometry(QRect(515, 515, 90, 30))
        self.Column6 = QLabel(self.centralwidget)
        self.Column6.setObjectName(u"Column6")
        self.Column6.setGeometry(QRect(550, 10, 20, 16))
        self.Column6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_4F = QLineEdit(self.centralwidget)
        self.lineEdit_4F.setObjectName(u"lineEdit_4F")
        self.lineEdit_4F.setGeometry(QRect(515, 155, 90, 30))
        self.lineEdit_2F = QLineEdit(self.centralwidget)
        self.lineEdit_2F.setObjectName(u"lineEdit_2F")
        self.lineEdit_2F.setGeometry(QRect(515, 75, 90, 30))
        self.lineEdit_7F = QLineEdit(self.centralwidget)
        self.lineEdit_7F.setObjectName(u"lineEdit_7F")
        self.lineEdit_7F.setGeometry(QRect(515, 275, 90, 30))
        self.lineEdit_12F = QLineEdit(self.centralwidget)
        self.lineEdit_12F.setObjectName(u"lineEdit_12F")
        self.lineEdit_12F.setGeometry(QRect(515, 475, 90, 30))
        self.lineEdit_8F = QLineEdit(self.centralwidget)
        self.lineEdit_8F.setObjectName(u"lineEdit_8F")
        self.lineEdit_8F.setGeometry(QRect(515, 315, 90, 30))
        self.lineEdit_9F = QLineEdit(self.centralwidget)
        self.lineEdit_9F.setObjectName(u"lineEdit_9F")
        self.lineEdit_9F.setGeometry(QRect(515, 355, 90, 30))
        self.lineEdit_6F = QLineEdit(self.centralwidget)
        self.lineEdit_6F.setObjectName(u"lineEdit_6F")
        self.lineEdit_6F.setGeometry(QRect(515, 235, 90, 30))
        self.lineEdit_3F = QLineEdit(self.centralwidget)
        self.lineEdit_3F.setObjectName(u"lineEdit_3F")
        self.lineEdit_3F.setGeometry(QRect(515, 115, 90, 30))
        self.lineEdit_11F = QLineEdit(self.centralwidget)
        self.lineEdit_11F.setObjectName(u"lineEdit_11F")
        self.lineEdit_11F.setGeometry(QRect(515, 435, 90, 30))
        self.lineEdit_10F = QLineEdit(self.centralwidget)
        self.lineEdit_10F.setObjectName(u"lineEdit_10F")
        self.lineEdit_10F.setGeometry(QRect(515, 395, 90, 30))
        self.lineEdit_1F = QLineEdit(self.centralwidget)
        self.lineEdit_1F.setObjectName(u"lineEdit_1F")
        self.lineEdit_1F.setGeometry(QRect(515, 35, 90, 30))
        self.lineEdit_6G = QLineEdit(self.centralwidget)
        self.lineEdit_6G.setObjectName(u"lineEdit_6G")
        self.lineEdit_6G.setGeometry(QRect(610, 235, 90, 30))
        self.lineEdit_13G = QLineEdit(self.centralwidget)
        self.lineEdit_13G.setObjectName(u"lineEdit_13G")
        self.lineEdit_13G.setGeometry(QRect(610, 515, 90, 30))
        self.lineEdit_11G = QLineEdit(self.centralwidget)
        self.lineEdit_11G.setObjectName(u"lineEdit_11G")
        self.lineEdit_11G.setGeometry(QRect(610, 435, 90, 30))
        self.lineEdit_12G = QLineEdit(self.centralwidget)
        self.lineEdit_12G.setObjectName(u"lineEdit_12G")
        self.lineEdit_12G.setGeometry(QRect(610, 475, 90, 30))
        self.Column7 = QLabel(self.centralwidget)
        self.Column7.setObjectName(u"Column7")
        self.Column7.setGeometry(QRect(645, 10, 20, 16))
        self.Column7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_9G = QLineEdit(self.centralwidget)
        self.lineEdit_9G.setObjectName(u"lineEdit_9G")
        self.lineEdit_9G.setGeometry(QRect(610, 355, 90, 30))
        self.lineEdit_3G = QLineEdit(self.centralwidget)
        self.lineEdit_3G.setObjectName(u"lineEdit_3G")
        self.lineEdit_3G.setGeometry(QRect(610, 115, 90, 30))
        self.lineEdit_5G = QLineEdit(self.centralwidget)
        self.lineEdit_5G.setObjectName(u"lineEdit_5G")
        self.lineEdit_5G.setGeometry(QRect(610, 195, 90, 30))
        self.lineEdit_7G = QLineEdit(self.centralwidget)
        self.lineEdit_7G.setObjectName(u"lineEdit_7G")
        self.lineEdit_7G.setGeometry(QRect(610, 275, 90, 30))
        self.lineEdit_8G = QLineEdit(self.centralwidget)
        self.lineEdit_8G.setObjectName(u"lineEdit_8G")
        self.lineEdit_8G.setGeometry(QRect(610, 315, 90, 30))
        self.lineEdit_1G = QLineEdit(self.centralwidget)
        self.lineEdit_1G.setObjectName(u"lineEdit_1G")
        self.lineEdit_1G.setGeometry(QRect(610, 35, 90, 30))
        self.lineEdit_2G = QLineEdit(self.centralwidget)
        self.lineEdit_2G.setObjectName(u"lineEdit_2G")
        self.lineEdit_2G.setGeometry(QRect(610, 75, 90, 30))
        self.lineEdit_4G = QLineEdit(self.centralwidget)
        self.lineEdit_4G.setObjectName(u"lineEdit_4G")
        self.lineEdit_4G.setGeometry(QRect(610, 155, 90, 30))
        self.lineEdit_10G = QLineEdit(self.centralwidget)
        self.lineEdit_10G.setObjectName(u"lineEdit_10G")
        self.lineEdit_10G.setGeometry(QRect(610, 395, 90, 30))
        self.lineEdit_9H = QLineEdit(self.centralwidget)
        self.lineEdit_9H.setObjectName(u"lineEdit_9H")
        self.lineEdit_9H.setGeometry(QRect(705, 355, 90, 30))
        self.lineEdit_7H = QLineEdit(self.centralwidget)
        self.lineEdit_7H.setObjectName(u"lineEdit_7H")
        self.lineEdit_7H.setGeometry(QRect(705, 275, 90, 30))
        self.lineEdit_12H = QLineEdit(self.centralwidget)
        self.lineEdit_12H.setObjectName(u"lineEdit_12H")
        self.lineEdit_12H.setGeometry(QRect(705, 475, 90, 30))
        self.lineEdit_10H = QLineEdit(self.centralwidget)
        self.lineEdit_10H.setObjectName(u"lineEdit_10H")
        self.lineEdit_10H.setGeometry(QRect(705, 395, 90, 30))
        self.lineEdit_11H = QLineEdit(self.centralwidget)
        self.lineEdit_11H.setObjectName(u"lineEdit_11H")
        self.lineEdit_11H.setGeometry(QRect(705, 435, 90, 30))
        self.lineEdit_13H = QLineEdit(self.centralwidget)
        self.lineEdit_13H.setObjectName(u"lineEdit_13H")
        self.lineEdit_13H.setGeometry(QRect(705, 515, 90, 30))
        self.Column8 = QLabel(self.centralwidget)
        self.Column8.setObjectName(u"Column8")
        self.Column8.setGeometry(QRect(740, 10, 20, 16))
        self.Column8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_6H = QLineEdit(self.centralwidget)
        self.lineEdit_6H.setObjectName(u"lineEdit_6H")
        self.lineEdit_6H.setGeometry(QRect(705, 235, 90, 30))
        self.lineEdit_3H = QLineEdit(self.centralwidget)
        self.lineEdit_3H.setObjectName(u"lineEdit_3H")
        self.lineEdit_3H.setGeometry(QRect(705, 115, 90, 30))
        self.lineEdit_5H = QLineEdit(self.centralwidget)
        self.lineEdit_5H.setObjectName(u"lineEdit_5H")
        self.lineEdit_5H.setGeometry(QRect(705, 195, 90, 30))
        self.lineEdit_1H = QLineEdit(self.centralwidget)
        self.lineEdit_1H.setObjectName(u"lineEdit_1H")
        self.lineEdit_1H.setGeometry(QRect(705, 35, 90, 30))
        self.lineEdit_4H = QLineEdit(self.centralwidget)
        self.lineEdit_4H.setObjectName(u"lineEdit_4H")
        self.lineEdit_4H.setGeometry(QRect(705, 155, 90, 30))
        self.lineEdit_8H = QLineEdit(self.centralwidget)
        self.lineEdit_8H.setObjectName(u"lineEdit_8H")
        self.lineEdit_8H.setGeometry(QRect(705, 315, 90, 30))
        self.lineEdit_2H = QLineEdit(self.centralwidget)
        self.lineEdit_2H.setObjectName(u"lineEdit_2H")
        self.lineEdit_2H.setGeometry(QRect(705, 75, 90, 30))
        self.SaveButton = QPushButton(self.centralwidget)
        self.SaveButton.setObjectName(u"SaveButton")
        self.SaveButton.setGeometry(QRect(350, 555, 100, 35))
        font = QFont()
        font.setBold(False)
        self.SaveButton.setFont(font)
        self.LoadButton = QPushButton(self.centralwidget)
        self.LoadButton.setObjectName(u"LoadButton")
        self.LoadButton.setGeometry(QRect(200, 555, 100, 35))
        self.ClearButton = QPushButton(self.centralwidget)
        self.ClearButton.setObjectName(u"ClearButton")
        self.ClearButton.setGeometry(QRect(500, 555, 100, 35))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Excel Manager 2.0", None))
        self.label1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.label8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.label9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.label10.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label11.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.label12.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label13.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.Column1.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.Column2.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.Column3.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.Column4.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.Column5.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.Column6.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.Column7.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.Column8.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.SaveButton.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
        self.LoadButton.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c", None))
        self.ClearButton.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0447\u0438\u0441\u0442\u0438\u0442\u044c", None))
    # retranslateUi

